### ISSUE TITLE
Find out how to close dialog by hand with shadcn components

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#121]

**Comment by mit-27** [comment]
Hello @naelob , I would like to work on this issue. Could you please assign this to me? Thank you

**Comment by naelob** [comment]
> Hello @naelob , I would like to work on this issue. Could you please assign this to me? Thank you

Yes ofc. Its done. A lot of dialog s/modals have the close button  working though some of them do not work specifically after adding a new connection for instance. In this case the auto close option provided by shadcn is not working and a manual close workaround may be needed.

**Comment by mit-27** [comment]
Sure, I will look into it

**Comment by mit-27** [comment]
Hello @naelob , I have identified issue but could you explain me the way I test it with backend. Is there a way that I could you local docker image of webapp in docker-compose.yml file ? Thank you

**Comment by naelob** [comment]
Yes normally you just have to follow the project running steps.

`cp .env.example .env
`
`docker compose up
`

**Comment by mit-27** [comment]
Actually I tried but it just pulling the image from registry and not creating an image from local webapp. So whatever changes I make to the webapp does not reflect when I run docker compose up.

**Comment by mit-27** [comment]
Hello @naelob, Could you let me know steps that I can follow and test my local Webapp changes? Thank you
