### ISSUE TITLE
ISSUE: webhooks are processed from the queue only when add happens

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#161]
When the server starts, the webhooks awaiting in the bull queue arent processed immediatly, it is done only when a new webhook enters the queue which is not convenient at all :
https://github.com/panoratech/Panora/tree/main/packages/api/src/%40core/webhook

check this file: https://github.com/panoratech/Panora/blob/main/packages/api/src/%40core/webhook/webhook.processor.ts

#

**Comment by JVFeijo** [comment]
Hi, @naelob. How are you?

I'm new here so I don't know if I'm doing this correctly and english is not my first language so I apologize for any misunderstanding beforehand.

So I was looking into the problem you stated and while reading the nest.js docs to understand the bull module they provide it is stated in the [consumers](https://docs.nestjs.com/techniques/queues#consumers) docs that whenever the worker is idle and there are jobs in the queue the processor should be called. Is this not happening then?

**Comment by mit-27** [comment]
Hello @naelob, I would like to work on this issue could you please assign this to me ? Thanks

**Comment by naelob** [comment]
> Hi, @naelob. How are you?
> 
> I'm new here so I don't know if I'm doing this correctly and english is not my first language so I apologize for any misunderstanding beforehand.
> 
> So I was looking into the problem you stated and while reading the nest.js docs to understand the bull module they provide it is stated in the [consumers](https://docs.nestjs.com/techniques/queues#consumers) docs that whenever the worker is idle and there are jobs in the queue the processor should be called. Is this not happening then?

hey thank youf or your answer ! I actually dont know beacuse even tho there a still a lot of jobs in the queue, the bull queue just process them once a new one is inserted it doesnt process all the remaining ones !

**Comment by mit-27** [comment]
Hi @naelob , could you please provide clear instructions on how to test webhook.processor.ts? I attempted to post a webhook via Swagger, but the logger messages in webhook.processor.ts aren't being printed. Thank you

**Comment by naelob** [comment]
> Hi @naelob , could you please provide clear instructions on how to test webhook.processor.ts? I attempted to post a webhook via Swagger, but the logger messages in webhook.processor.ts aren't being printed. Thank you

This is exactly the error. The job is processed only when you add something inside it and its processing only past jobs not the one you add at instant t.

**Comment by mit-27** [comment]
> > Hi @naelob , could you please provide clear instructions on how to test webhook.processor.ts? I attempted to post a webhook via Swagger, but the logger messages in webhook.processor.ts aren't being printed. Thank you
> 
> This is exactly the error. The job is processed only when you add something inside it and its processing only past jobs not the one you add at instant t.

Got it ! I am looking into this

**Comment by mit-27** [comment]
Hi @naelob , could you please provide instructions on how to set up a working webhook in Panora? I want to be able to monitor when the webhook processes data through webhook.processor.ts. Since I'm having trouble establishing a connection using the Magic link, I'm wondering how I can verify when the webhook is triggered and successfully delivers the data.

**Comment by naelob** [comment]
> webhook

Yes sure. Just add a webhook using this site => https://webhook.site/#!/view/65f940b9-7714-4b76-9e35-dfc9c38c9ee6 for having a url to log data sent to the webhook.
And to register this webhook inside the panora backend you must call these:

```
async createWebhookEndpoint(data: WebhookDto) {
    try {
      return await this.prisma.webhook_endpoints.create({
        data: {
          id_webhook_endpoint: uuidv4(),
          url: data.url,
          endpoint_description: data.description ? data.description : '',
          secret: uuidv4(),
          active: true,
          created_at: new Date(),
          id_project: data.id_project,
          scope: data.scope,
        },
      });
    } catch (error) {
      handleServiceError(error, this.logger);
    }
  }
```
```
interface IWebhookDto {
    url: string;
    description?: string;
    id_project: string;
    scope: string[];
}
```

so when you have your webhook created then each time a new data is fetched from a crm from instance automatically a job is added to the queue so it can be relayed to the sender that created the webhook on the url you've specified.

here is the code where a webhook is added:

https://github.com/panoratech/Panora/blob/2e859790fb3f13cd68d0494a5429a532e90faa3d/packages/api/src/crm/contact/sync/sync.service.ts#L171C1-L172C1

Our issue is that right now jobs are processed only when the handleWebhook is called so there is a discrepancy :
if i have 10 jobs (job 1, job2, ...., job 10) in the queue at time = t
if i add a new job, there are 11 jobs (job 11) at time = t +1
=> only the job 1 from the past is processed and not the 10 remaining.

expected behaviour: all jobs waiting in the queue are processed sequentially OR asynchronously.

Hope its clear.

**Comment by mit-27** [comment]
> > webhook
> 
> Yes sure. Just add a webhook using this site => https://webhook.site/#!/view/65f940b9-7714-4b76-9e35-dfc9c38c9ee6 for having a url to log data sent to the webhook. And to register this webhook inside the panora backend you must call these:
> 
> ```
> async createWebhookEndpoint(data: WebhookDto) {
>     try {
>       return await this.prisma.webhook_endpoints.create({
>         data: {
>           id_webhook_endpoint: uuidv4(),
>           url: data.url,
>           endpoint_description: data.description ? data.description : '',
>           secret: uuidv4(),
>           active: true,
>           created_at: new Date(),
>           id_project: data.id_project,
>           scope: data.scope,
>         },
>       });
>     } catch (error) {
>       handleServiceError(error, this.logger);
>     }
>   }
> ```
> 
> ```
> interface IWebhookDto {
>     url: string;
>     description?: string;
>     id_project: string;
>     scope: string[];
> }
> ```
> 
> so when you have your webhook created then each time a new data is fetched from a crm from instance automatically a job is added to the queue so it can be relayed to the sender that created the webhook on the url you've specified.
> 
> here is the code where a webhook is added:
> 
> https://github.com/panoratech/Panora/blob/2e859790fb3f13cd68d0494a5429a532e90faa3d/packages/api/src/crm/contact/sync/sync.service.ts#L171C1-L172C1
> 
> Our issue is that right now jobs are processed only when the handleWebhook is called so there is a discrepancy : if i have 10 jobs (job 1, job2, ...., job 10) in the queue at time = t if i add a new job, there are 11 jobs (job 11) at time = t +1 => only the job 1 from the past is processed and not the 10 remaining.
> 
> expected behaviour: all jobs waiting in the queue are processed sequentially OR asynchronously.
> 
> Hope its clear.

Thank you so much @naelob for explaining in detail. The main issue that I am having is that I could not able to create hubspot connection via magic link and as reason I am not able to fetch the contacts and trigger the webhook. 

Is there an other way that I can fetch crm/cotacts so the associated webhook gets triggered ?

**Comment by mit-27** [comment]
@naelob, you may close this issue as resolved since the queue effectively handles all the webhooks' tasks we've inserted into it. If you want I can add a small demo video within this discussion.
