### ISSUE TITLE
fix the refresh state updates in webapp

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#170]
(WEBAPP)
Each time the backend server is updated, the data is not being re-rendered on the frontend without a hard refresh !

It may be related to useEffect hooks.

**Comment by mit-27** [comment]
Hello @naelob, I would like to work on the issue. Thank you

**Comment by naelob** [comment]
> Hello @naelob, I would like to work on the issue. Thank you

@mit-27 Awesome ! I'd check that asap once you open the PR !
For this one you would need to have the server started so let me know if you know how to to do it to make your tests !

**Comment by mit-27** [comment]
Hello @naelob , I think there is an issue in docker-compose.dev.yml file that it was throwing errors.

**Comment by naelob** [comment]
> Hello @naelob , I think there is an issue in docker-compose.dev.yml file that it was throwing errors.

@mit-27 Hey mit ! It would be awesome if this issue was resolved. Do you still have issue running locally the project ? 
Here is a good guide:
https://docs.panora.dev/open-source/self-host-guide

**Comment by mit-27** [comment]
Hello @naelob ! I was not able to run project by following this link : https://docs.panora.dev/open-source/contributors
There was a some mistakes in docker-compose.dev.yml. I ran the project by fixing those issues (I will open Pull request to resolve the problem). However, I am not able to add any data as it was showing Unexpected end of json input. Could you looked into it. Thanks

**Comment by naelob** [comment]
> Hello @naelob ! I was not able to run project by following this link : https://docs.panora.dev/open-source/contributors There was a some mistakes in docker-compose.dev.yml. I ran the project by fixing those issues (I will open Pull request to resolve the problem). However, I am not able to add any data as it was showing Unexpected end of json input. Could you looked into it. Thanks

what do you mean about the issue ? could you elaborate directly on discord ?

**Comment by mit-27** [comment]
I already sent a message on discord. Could you look into that ?
