### ISSUE TITLE
Add a magic link button field

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#202]
If the magic link generated on the webapp isnt used at first time or the oAuth flow failed (the user failed to grant access to his tool or he just didnt do it properly), make sure to keep the generated id of the magic link and just display it in the configuration page where all linked users are displayed.

You have to display it under the linkedUser name that failed to do the flow described above.

**Comment by Sachinsharma01** [comment]
the above statement is unclear can you explain more? can you provide more insights to this issue

**Comment by naelob** [comment]
Is it better ? 
ps: the magic link generation is done once you click on Connections tab and you add a new connection.

**Comment by Sachinsharma01** [comment]
few questions I have 
 - How do you identify that the link isn't used for the first time? does BE send the key
 - Again for point 2 is the oauth flow failed then how does FE know, does BE send the key ?
