### ISSUE TITLE
Handle oauth success status

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#225]
IN PRIORITY DO ONLY 1. 
1. Inside 
https://github.com/panoratech/Panora/tree/main/apps/embedded-catalog/react when someone finishes the flow make sure to make the client aware with an slick ui animation. You might need to update the `src/packages/shared`

2. Once you go through the oAuth flow, you cant do it again unless oauth access has been revoked in the end-user account.
Make sure to check that

3. link a unified data internally to an id_connection not a linkedUser

**Comment by Neerajrawat123** [comment]
Hello Team , 
I really want to contribute to project but i am new in open-source .
can anyone mentor me how to  do it.
