### ISSUE TITLE
Add a way to customize api url where server is running inside embedded catalog

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#272]
Inside https://github.com/panoratech/Panora/tree/main/apps/embedded-catalog/react 
When someones from the outside use it, if he's in selfhosted mode he may want to use it with his server.

Right now it's in the managed cloud mode where the api url is hardcoded.
(cf: https://github.com/panoratech/Panora/blob/main/apps/embedded-catalog/react/src/helpers/config.ts)

FInd a way to add an api url if in selfhost mode (with a optional prop ?)

**Comment by mit-27** [comment]
Hello @naelob, I am working on it and I will create the PR asap.

**Comment by mit-27** [comment]
Hello @naelob, should I proceed with updating the Readme.md of the embedded-catalog component to include information about the optional Server URL prop?

**Comment by naelob** [comment]
> Hello @naelob, should I proceed with updating the Readme.md of the embedded-catalog component to include information about the optional Server URL prop?

ok thank you ! Did you open a PR for this ?

**Comment by naelob** [comment]
> > > Hello @naelob, should I proceed with updating the Readme.md of the embedded-catalog component to include information about the optional Server URL prop?
> > 
> > 
> > ok thank you ! Did you open a PR for this ?
> 
> Yes, I opened PR #291 . But first I would like to check my implementation and if its correct then I will update readme according to it.

which readme ?

**Comment by mit-27** [comment]
> > > > Hello @naelob, should I proceed with updating the Readme.md of the embedded-catalog component to include information about the optional Server URL prop?
> > > 
> > > 
> > > ok thank you ! Did you open a PR for this ?
> > 
> > 
> > Yes, I opened PR #291 . But first I would like to check my implementation and if its correct then I will update readme according to it.
> 
> which readme ?

The component's readme - https://github.com/panoratech/Panora/tree/main/apps/embedded-catalog/react

**Comment by naelob** [comment]
> > > > > Hello @naelob, should I proceed with updating the Readme.md of the embedded-catalog component to include information about the optional Server URL prop?
> > > > 
> > > > 
> > > > ok thank you ! Did you open a PR for this ?
> > > 
> > > 
> > > Yes, I opened PR #291 . But first I would like to check my implementation and if its correct then I will update readme according to it.
> > 
> > 
> > which readme ?
> 
> The component's readme - https://github.com/panoratech/Panora/tree/main/apps/embedded-catalog/react

yes exactly ! Thank you very much
