### ISSUE TITLE
Sync Organization data between Stytch Auth API and Panora Backend

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#319]
We have to sync organizations created through stytch (used for auth) and the ornganizations we have internally in our db.

The idea is to be able to map 1:1 all the orgs from stytch with Panora so there are no discrepancies.

**Comment by rflihxyz** [comment]
We can simply use a Webhook for that. Should be enough for this type of data

**Comment by naelob** [comment]
> We can simply use a Webhook for that. Should be enough for this type of data and volume

So we dont let ppl create panora organizations through our app right ? 
(only through stytch ?)
