### ISSUE TITLE
[Ticketing] Github connector

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#327]
Build an integration between our Ticketing Unified API and Github.

Expected unified objects are: 

- [ ] Tickets
- [ ] Comments
- [ ] Users
- [ ] Contacts
- [ ] Tags
- [ ] Teams
- [ ] Project
- [ ] Collection

Github's documentation can be found [here](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app)

**Comment by Gmin2** [comment]
Hey @rflihxyz working on it

**Comment by naelob** [comment]
> Hey @rflihxyz working on it

sonds good ! let me know if any questions !

**Comment by hrutik7** [comment]
hey @mit-27 are you working on this ?
@naelob would love to work on this :)
