### ISSUE TITLE
Feat: Snowflake pls :3

### ISSUE THREAD

**Issue by jdbohrman** [panoratech/Panora#337]
This would be the thing that puts Panora above all the others. I can help. This is something I need for my current project.

**Comment by jdbohrman** [comment]
Magic links + Snowflake would be a game changer

**Comment by naelob** [comment]
Ok let me finish my big PR that is updating the whole project and after that you can work on it.

**Comment by rflihxyz** [comment]
Hey @jdbohrman , do you have some time for a quick chat about how you're planning to use Panora ? That would help us build the best product in the space!  Please book some time in [my calendar here](https://cal.com/rflih/15)

Thank you!

**Comment by pardaz-banu** [comment]
Hi @rflihxyz, my team and I would like to work on this. Could you please assign this to us?

**Comment by rflihxyz** [comment]
> Hi , my team and I would like to work on this. Could you please assign this to us?

Done @pardaz-banu ;)

**Comment by lloydchang** [comment]
> > Hi , my team and I would like to work on this. Could you please assign this to us?
> 
> Done @pardaz-banu ;)

Thanks, @rflihxyz!

Great meeting you during Headstarter's Zoom meeting.

Take care! 🙂

( Cc: My teammates @pardaz-banu and @halifrieri )

**Comment by lloydchang** [comment]
My teammates @pardaz-banu , @halifrieri , @toluwalopeoolagbegi , and @tushcmd are starting to consider this. We've had competing priorities previously.

**Comment by lloydchang** [comment]
**Context:** Panora seems to be transitioning and pivoting from:

> Ship all the integrations your customers need in hours, not months

and

> One API to connect your data sources to your LLMs

towards

> All your eCommerce and warehouse operations under a single API.
>
> Introducing Panora – the API that helps your organization connect your stores and warehouses seamlessly.

**Question:** Is this feature request still relevant considering Panora's new direction and focus on eCommerce and warehouse operations?

**Suggestion:** If this feature request is no longer relevant to Panora, then I suggest closing it as "Won't Do".

**Comment by rflihxyz** [comment]
> **Context:** Panora seems to be transitioning and pivoting…
> 
> from:
> 
> 
> > Ship all the integrations your customers need in hours, not months
> 
> 
> > One API to connect your data sources to your LLMs
> 
> towards:
> 
> 
> > Hello the current Cloud product has been suspended. Major updates are coming. Lots of security patches, and in the future, Panora's focus will be on ecommerce, and Warehouse management systems!
> 
> 
> > All your eCommerce and warehouse operations under a single API.
> > Introducing Panora – the API that helps your organization connect your stores and warehouses seamlessly.
> 
> **Question:** Is this feature request — Feat: Snowflake pls :3 #337 — still relevant considering Panora's new direction and focus on eCommerce and warehouse operations?
> 
> **Suggestion:** If this feature request is no longer relevant to Panora, then I suggest closing it as "Won't Do".

Hi, this is right, those were the main evolutions of our product. I am going to close the issue.

For your interest:
Those three next months will be focused on e-commerce, and warehouse management systems. 
Those areas are where we've seen the biggest demand. An AI Agent might also be added to the roadmap (basically able to turn proof of deliveries and other unstructured data into data that can be inserted into a WMS / Ecommerce). 
In the immediate next days, the priority will be patching Panora to make it production ready. The former CTO has been fired, and more than 100 security issues were found in the code. (see #712  and #713 )
