### ISSUE TITLE
feat: Add Gitlab integration to ticketing vertical

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#367]
feat: Add Gitlab integration to ticketing vertical

Expected objets are: 

- [x] Collections
- [x] Comments
- [ ] Tags
  - It is not compatible with Panora's Unified Model. The tag should be associated with the ticket (issue). However, for GitLab, tags are associated with individual projects, which makes it incompatible with Panora's Unified Model.
- [x] Tickets
- [x] Users

Please find details about how to build integrations [here](https://docs.panora.dev/open-source/contributors) . Our [discord](https://discord.gg/feRW57Ym3D)  community is also a great place to get support!

**Comment by neo773** [comment]
Can I get assigned?

**Comment by rflihxyz** [comment]
> Can I get assigned?

Assigned!

**Comment by naelob** [comment]
You can find all information about Gitlab here 👍
https://github.com/panoratech/Panora/blob/db5d916fe0c77c5c00bb2c5359a5d90a7ac68266/packages/shared/src/utils.ts#L397

**Comment by webbdays** [comment]
in queue.

**Comment by webbdays** [comment]
@rflihxyz
are you still on this?

**Comment by neo773** [comment]
Yes

**Comment by webbdays** [comment]
ok.
sorry wrong mention.

**Comment by rflihxyz** [comment]
Hey @neo773 any progress on this Gitlab connector? We're available to provide help!

**Comment by neo773** [comment]
@rflihxyz 
Replied on Discord!

**Comment by lakshya-dhariwal** [comment]
Is someone working on this or can I pick this up?

**Comment by neo773** [comment]
@lakshya-dhariwal 
Feel free to pick this up

**Comment by jordan-ae** [comment]
@rflihxyz I want to give this a try!

**Comment by rflihxyz** [comment]
Hey @jordan-ae, just assigned you this issue, feel free to ask for help about anything here or on [our Discord](https://discord.gg/feRW57Ym3D)

@naelob

**Comment by jordan-ae** [comment]
@rflihxyz jumping on it immediately

**Comment by jordan-ae** [comment]
> Don't forget to declare your attempt (instructions above) @jordan-ae 

Done thanks

**Comment by mit-27** [comment]
Hello @naelob and @rflihxyz , 

**Guildlines for creating integration issues**
- It is necessary to mention what we are expecting from each unified object. Because every third party has a different implementation for the unified object. For instance, the collection object is identified as a project in GitLab.
- Also, we also have to mention what would be the expected result from Unified API endpoints for each object. This would help fellow contributors to set correct third-party endpoints.

**Gitlab Unified objects Detail**
- Users (ticketing/users)
  - Object in context of third-party(Gitlab) - Users
  - GET - Fetches the list of users of GitLab.
- Collections (ticketing/collections)
  - Object in context of third-party(Gitlab) - Projects
  - GET API - Get a list of all visible projects across GitLab for the authenticated user.
- Tickets (ticketing/tickets)
  - Object in context of third-party(Gitlab) - Issues
  - GET API - Get a list of issues created and assigned to authenticated users.
  - POST API - Create an issue for a specific project by providing the project ID in post data (type of UnifiedTicket object).
- Comments (ticketing/comments)
  - Object in the context of third-party(Gitlab) - Comments on issues that are created or assigned to authenticated users.
  - GET API - Get a list of comments on issues that are created or assigned to authenticated users.
  - POST API - Post a comment on an issue by mentioning ticket_id in post data (type of UnifiedComment object).

**Comment by naelob** [comment]
> Hello @naelob and @rflihxyz ,
> 
> **Guildlines for creating integration issues**
> 
> * It is necessary to mention what we are expecting from each unified object. Because every third party has a different implementation for the unified object. For instance, the collection object is identified as a project in GitLab.
> * Also, we also have to mention what would be the expected result from Unified API endpoints for each object. This would help fellow contributors to set correct third-party endpoints.
> 
> **Gitlab Unified objects Detail**
> 
> * Users (ticketing/users)
>   
>   * Object in context of third-party(Gitlab) - Users
>   * GET - Fetches the list of users of GitLab.
> * Collections (ticketing/collections)
>   
>   * Object in context of third-party(Gitlab) - Projects
>   * GET API - Get a list of all visible projects across GitLab for the authenticated user.
> * Tickets (ticketing/tickets)
>   
>   * Object in context of third-party(Gitlab) - Issues
>   * GET API - Get a list of issues created and assigned to authenticated users.
>   * POST API - Create an issue for a specific project by providing the project ID in post data (type of UnifiedTicket object).
> * Comments (ticketing/comments)
>   
>   * Object in the context of third-party(Gitlab) - Comments on issues that are created or assigned to authenticated users.
>   * GET API - Get a list of comments on issues that are created or assigned to authenticated users.
>   * POST API - Post a comment on an issue by mentioning ticket_id in post data (type of UnifiedComment object).
> 
> **Let me know if any changes are required for any object.**

I rea the guidelines you propose but doing so is not efficient. It means doing all the work for the contributor. This is actually the manual task to understand which object to grab from the 3rd party. If we do that no need to have contributors in the first place... It's a tricky task but this is why we have to gain it from the community.

Let me know your thoughts

**Comment by mit-27** [comment]
> > Hello @naelob and @rflihxyz ,
> > **Guildlines for creating integration issues**
> > 
> > * It is necessary to mention what we are expecting from each unified object. Because every third party has a different implementation for the unified object. For instance, the collection object is identified as a project in GitLab.
> > * Also, we also have to mention what would be the expected result from Unified API endpoints for each object. This would help fellow contributors to set correct third-party endpoints.
> > 
> > **Gitlab Unified objects Detail**
> > 
> > * Users (ticketing/users)
> >   
> >   * Object in context of third-party(Gitlab) - Users
> >   * GET - Fetches the list of users of GitLab.
> > * Collections (ticketing/collections)
> >   
> >   * Object in context of third-party(Gitlab) - Projects
> >   * GET API - Get a list of all visible projects across GitLab for the authenticated user.
> > * Tickets (ticketing/tickets)
> >   
> >   * Object in context of third-party(Gitlab) - Issues
> >   * GET API - Get a list of issues created and assigned to authenticated users.
> >   * POST API - Create an issue for a specific project by providing the project ID in post data (type of UnifiedTicket object).
> > * Comments (ticketing/comments)
> >   
> >   * Object in the context of third-party(Gitlab) - Comments on issues that are created or assigned to authenticated users.
> >   * GET API - Get a list of comments on issues that are created or assigned to authenticated users.
> >   * POST API - Post a comment on an issue by mentioning ticket_id in post data (type of UnifiedComment object).
> > 
> > **Let me know if any changes are required for any object.**
> 
> I rea the guidelines you propose but doing so is not efficient. It means doing all the work for the contributor. This is actually the manual task to understand which object to grab from the 3rd party. If we do that no need to have contributors in the first place... It's a tricky task but this is why we have to gain it from the community.
> 
> What I propose would be a 2-sided task where 1 community member can do the detailed object information (which will be incentivized of course but < than the final task) and another one could build it upon that work.
> 
> Let me know your thoughts

Yes @naelob, I think that would make sense. Also, we can validate the object information provided by community members to ensure that the integration will be built correctly.

**Comment by rajeshj11** [comment]
@mit-27 your changes are merged. I can't find any issue raised related to pagination. can you please provide me with the ticket?

**Comment by mit-27** [comment]
> @mit-27 your changes are merged. I can't find any issue raised related to pagination. can you please provide me with the ticket?

I just checked. That was for specific provider. Can you open an issue ?

**Comment by rajeshj11** [comment]
> > @mit-27 your changes are merged. I can't find any issue raised related to pagination. can you please provide me with the ticket?
> 
> I just checked. That was for specific provider. Can you open an issue ?

Let the internal team raise the issue.
