### ISSUE TITLE
Update the Doc

### ISSUE THREAD

**Issue by mit-27** [panoratech/Panora#369]
These are the points that need to be added in doc.

- [ ] Add instruction to set Stytch credentials in env file for Authentication - **(Under Open Source Section)**
- [ ] Mention both the ways to provide custom credentials of a provider.
    1. Using .env file
    2. Adding custom credentials via **0Auth Credentials** section which is available on **configuration Page**.  **(We must mention that by default it is only using the 0Auth2 type authentication method)**

**Comment by rflihxyz** [comment]
We should not force people to create a Stytch account on the OSS version. How hard would it be to have stytch on our cloud version and a basic user/pass on the OSS?

**Comment by mit-27** [comment]
Yes, it can be done easily. I think @naelob already disabled protected routes for selfhosted version.

**Comment by mit-27** [comment]
Sure, understood. Let me know, If you require help with migration. I'll focus on the backend tasks until the migration process is complete.
