### ISSUE TITLE
Correct API Requests to Show Data Based on Logged-In User

### ISSUE THREAD

**Issue by mit-27** [panoratech/Panora#405]
**Issue**
- Right now, the app fetches and shows all data to any user who's logged in. But these specific items should only be fetched by the user who's currently logged in:
  - Connections
  - API Keys
  - Linked Users
  - Events
  - Webhooks
  - Field Mapping

**Solution**
- Each object should be by the currently logged-in user or its associated project ID
  
- [ ] Connections - Fetch them using project IDs of the current User
- [ ] API Keys - Fetch them using the current user's ID
- [ ] Linked Users - Fetch them using project IDs of current User
- [ ] Events - Fetch them using linked users of projects created by the current User
- [ ] Webhooks - Fetch them using project IDs of the current User
- [ ] Field Mapping -  It remains unclear what criteria I should use to fetch them.

**Comment by mit-27** [comment]
Hello @rflihxyz and @naelob , please review the proposed solution and inform me if any changes are required. Thank you

**Comment by rflihxyz** [comment]
Hey, I think the best in terms of UX and ease of implementation would be creating a default project for users on signup.

That way, on signup, and post-login, we can return a JWT token that identifies the user and the project.

Users will be able to switch projects from their dashboard by clicking on one from the menu. Clicking on a project will fire a GET request, to obtain a new JWT token that includes the selected project id. 

ex: GET http://localhost:3000/auth/set_project?id_project=<some project id>

(this route checks reads the JWT token, and returns a new one if the user has access rights to requested project)

**Comment by mit-27** [comment]
Correct me if I am wrong @rflihxyz , we are displaying and fetching projects using current userID which means the current user already has right access to it. so why should we again check the project ID for current User ?

**Comment by rflihxyz** [comment]
Various ressources (connections, linked_users) belong to a project entity. 

Then around the project entity we have users, which could belong to organizations in the future
