### ISSUE TITLE
Handle Pagination For Gitlab Connector.

### ISSUE THREAD

**Issue by rajeshj11** [panoratech/Panora#428]
**Describe the bug**
While I was addressing bounty ticket #367 , it seems that @mit-27  completed it ahead of me. However, it appears that some changes related to pagination were missed during the initial completion. Since I've already invested time in understanding and implementing pagination for this ticket, I'd like to review and address any necessary fixes if needed, to ensure that the solution meets the project requirements thoroughly.

**screenshots**
![Screenshot from 2024-05-14 21-54-24](https://github.com/panoratech/Panora/assets/38752904/911bc9eb-ea36-4873-b709-6e3df2c3ee36)

**Additional context**
1. Gitlab integration needs pagination handling.
2. While syncing it may encounter http status 500 error as we hit the API multiple times. so it needs retry mechanism.

https://docs.gitlab.com/ee/api/rest/index.html#pagination

**Comment by rajeshj11** [comment]
@rflihxyz ^^ Please assign it to me if it is a valid issue.

**Comment by naelob** [comment]
@rajeshj11 Ok cool ! work on it considering @mit-27 's work and I'll compensate as well !

**Comment by rajeshj11** [comment]
Thanks , will raise pr and let you know

**Comment by rajeshj11** [comment]
@naelob please review https://github.com/panoratech/Panora/pull/429

**Comment by rflihxyz** [comment]
Hello, @rajeshj11 

Thanks for that contribution! We really do appreciate that. We're currently evaluating multiple types of pagination for our API : cursor-based, and offset based. We haven't made a decision yet about which approach to take, for that reason, we can not accept this contribution immediately. 

Do you want us to update you once we move to that feature? 
I just created [this issue](https://github.com/panoratech/Panora/issues/430) to discuss it.
