### ISSUE TITLE
feat: Add integration with Affinity (CRM)

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#448]
### Category

CRM

### Platforms

[Affinity](https://www.affinity.co/)
[API Docs](https://api-docs.affinity.co/#introduction)

## Objects

- [ ] Account
- [ ] Contact
- [ ] Note
- [ ] Deal

If needed, you can [ask Panora's team for credentials here](https://airtable.com/appUOCIdiEcBaZWMd/pagFdwXOv5BsVPFv0/form)

**Comment by Gmin2** [comment]
Hey @rflihxyz can i take this

**Comment by rflihxyz** [comment]
Yes!  please proceed!

**Comment by developerdhruv** [comment]
/attempt #448
Hey @rflihxyz, I want to work on it can integrate it seamlessly, Please assign this to me.
Thank You

**Comment by animeshd9** [comment]
/attempt #448

Can I take this issue @rflihxyz

**Comment by Gmin2** [comment]
I was assigned to this issue @developerdhruv

**Comment by developerdhruv** [comment]
Hey @Gmin2  In this bounty based issue anyone can do contribution it doesnt matter whether you are assigned or not, its just about contribution and also i already raised message that i will be working on this issue, Please check.

**Comment by Gmin2** [comment]
> Hey @Gmin2 In this bounty based issue anyone can do contribution it doesnt matter whether you are assigned or not, its just about contribution and also i already raised message that i will be working on this issue, Please check.

are yu serious?

**Comment by developerdhruv** [comment]
See Multiple people are taking this issue through algora method so i also took it and sorry if you dont like it,  but in bounties there is a competition who solves issue faster.

**Comment by developerdhruv** [comment]
Listen you should also submit your PR soon you will also get bounties because in many case more than 1 pr got bounties.

**Comment by Gmin2** [comment]
@rflihxyz your call

**Comment by rflihxyz** [comment]
Hello @Gmin2 , and @developerdhruv 

Anyone is welcome to contribute to Panora.  The bounties are here to thank members of the community who contributed. 

We do not give any exclusivity or advantages to anyone, each member is equal. We will payout the bounty to the first talent who will be able to ship the code, as simple as that. 

If there are multiple pull requests for a same issue, we process pull requests in chronological order, until one passes all our internal checks.

hope this clarifies the situation for you guys 🙏

**Comment by rflihxyz** [comment]
Hey @Gmin2 any news on this issue?

**Comment by Gmin2** [comment]
> Hey @Gmin2 any news on this issue?

@developerdhruv on it

**Comment by STSonyThomas** [comment]
Hey is this still open?

**Comment by MuhmdAjeer** [comment]
hey @rflihxyz, is this still open ?

**Comment by KshitijBhardwaj18** [comment]
@rflihxyz whats the status on this
