### ISSUE TITLE
feat: Add integration with: Deel (HR)

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#450]
### Category

HRIS

### Platforms

Platform : Deel
Objects:
Read vs Write:

**Comment by tiagoapolo** [comment]
@rflihxyz do you have more info on this issue? Which objects we want to fetch first?

**Comment by rflihxyz** [comment]
> @rflihxyz do you have more info on this issue? Which objects we want to fetch first?

@tiagoapolo We're currently identifying which objects are the most important. Do you have experience working with Deel/HR software? Your ideas are more than welcome!

**Comment by tiagoapolo** [comment]
I have not integrated Deel before, but I was l looking over and it's pretty standard, I'd be happy to help out integrating this one once you guys figured which objects are relevant for this initial version.

**Comment by rflihxyz** [comment]
We'll keep you updated about that @tiagopolo! Is there any other integration you'd be excited to work on in the meantime? We have some CRMs issues open ([here](https://github.com/panoratech/Panora/issues?q=is%3Aopen+label%3A%22%F0%9F%94%8C+Connector%22+CRM))
