### ISSUE TITLE
feat: Add integration with Close CRM

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#455]
### Category
CRM

### Platforms
Close.com

### Expected Objects

- [ ] Account
- [ ] Contact
- [ ] Engagement
- [ ] Engagement Type
- [ ] Note
- [ ] Deal
- [ ] Stage
- [ ] Task
- [ ] User

**Comment by rflihxyz** [comment]
Hey @lovishduggal, our community can help you build this connector - feel free to checkout [our discord](https://discord.gg/PH5k7gGubt) to receive support

**Comment by abhishek818** [comment]
@rflihxyz  Can i get this assigned ? Seems the other guy closed his attempt.

**Comment by lovishduggal** [comment]
Hey @rflihxyz! After reviewing my work, I've realized that I wasn't aware you were using nestJS. Currently, I'm more familiar with MERN and NextJS, but I'm really interested in learning nestJS in the near future. Once I've gained proficiency in it, I'd love to circle back to your project and contribute. Thank you for being so understanding and accommodating.
