### ISSUE TITLE
Not getting list of applications in magic link

### ISSUE THREAD

**Issue by arkanoid17** [panoratech/Panora#488]
Hi, I have been trying to create a magic link to create a CRM integration but after the link is generated no applications are showing up as can bee seen in the screenshot below.

<img width="1440" alt="Screenshot 2024-06-06 at 6 30 23 PM" src="https://github.com/panoratech/Panora/assets/26703458/1f7626d8-ee02-471f-819a-6cbaccd87e07">

Also I keep getting this issue in the terminal saying

` err: {
api-1                  |       "type": "NotFoundException",
api-1                  |       "message": "Connectors not found for current project!",
api-1                  |       "stack":
api-1                  |           NotFoundException: Connectors not found for current project!
api-1                  |               at ProjectConnectorsService.getConnectorsByProjectId (/app/packages/api/dist/src/@core/project-connectors/project-connectors.service.js:91:23)
api-1                  |               at async ProjectConnectorsController.getConnectorsFromProject (/app/packages/api/dist/src/@core/project-connectors/project-connectors.controller.js:39:16)
api-1                  |       "response": {
api-1                  |         "type": "Object",
api-1                  |         "message": "Connectors not found for current project!",
api-1                  |         "stack":
api-1                  |             
api-1                  |         "error": "Not Found",
api-1                  |         "statusCode": 404
api-1                  |       },
api-1                  |       "status": 404,
api-1                  |       "options": {},
api-1                  |       "name": "NotFoundException"
api-1                  |     }
api-1                  | Req data is: {
api-1                  |   id_user: '5de5e7f2-aee8-4114-b7e3-a1dc5e67e87a',
api-1                  |   email: 'arkaprabha.mahata@adjoint.in',
api-1                  |   first_name: 'Arkaprabha',
api-1                  |   last_name: 'Mahata',
api-1                  |   id_project: 'acb1a3a8-f868-42c4-9040-68db6be5057f'
api-1                  | }
`

It would  be very helpful if you can resolve this quickly. Thnak you again

**Comment by naelob** [comment]
> Hi, I have been trying to create a magic link to create a CRM integration but after the link is generated no applications are showing up as can bee seen in the screenshot below.
> 
> <img alt="Screenshot 2024-06-06 at 6 30 23 PM" width="1440" src="https://private-user-images.githubusercontent.com/26703458/337273704-1f7626d8-ee02-471f-819a-6cbaccd87e07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Nzk5MzMsIm5iZiI6MTcxNzY3OTYzMywicGF0aCI6Ii8yNjcwMzQ1OC8zMzcyNzM3MDQtMWY3NjI2ZDgtZWUwMi00NzFmLTgxOWEtNmNiYWNjZDg3ZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEzMTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTE1YjY4NTgyMWNmNDcxNDM0NzU3ZTkyZjRhNjZiMmQzYmRlMWZkNDFiNGY0NDAwNTAwMGRhMjIwNmQyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ijomFsiVuMBD9KqCA0sWBaT2I8QYPNrGtM98UrAimWU">
> Also I keep getting this issue in the terminal saying
> 
> `err: { api-1 | "type": "NotFoundException", api-1 | "message": "Connectors not found for current project!", api-1 | "stack": api-1 | NotFoundException: Connectors not found for current project! api-1 | at ProjectConnectorsService.getConnectorsByProjectId (/app/packages/api/dist/src/@core/project-connectors/project-connectors.service.js:91:23) api-1 | at async ProjectConnectorsController.getConnectorsFromProject (/app/packages/api/dist/src/@core/project-connectors/project-connectors.controller.js:39:16) api-1 | "response": { api-1 | "type": "Object", api-1 | "message": "Connectors not found for current project!", api-1 | "stack": api-1 | api-1 | "error": "Not Found", api-1 | "statusCode": 404 api-1 | }, api-1 | "status": 404, api-1 | "options": {}, api-1 | "name": "NotFoundException" api-1 | } api-1 | Req data is: { api-1 | id_user: '5de5e7f2-aee8-4114-b7e3-a1dc5e67e87a', api-1 | email: 'arkaprabha.mahata@adjoint.in', api-1 | first_name: 'Arkaprabha', api-1 | last_name: 'Mahata', api-1 | id_project: 'acb1a3a8-f868-42c4-9040-68db6be5057f' api-1 | }`
> 
> It would be very helpful if you can resolve this quickly. Thnak you again

I just merged a PR

> Hi, I have been trying to create a magic link to create a CRM integration but after the link is generated no applications are showing up as can bee seen in the screenshot below.
> 
> <img alt="Screenshot 2024-06-06 at 6 30 23 PM" width="1440" src="https://private-user-images.githubusercontent.com/26703458/337273704-1f7626d8-ee02-471f-819a-6cbaccd87e07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Nzk5MzMsIm5iZiI6MTcxNzY3OTYzMywicGF0aCI6Ii8yNjcwMzQ1OC8zMzcyNzM3MDQtMWY3NjI2ZDgtZWUwMi00NzFmLTgxOWEtNmNiYWNjZDg3ZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEzMTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTE1YjY4NTgyMWNmNDcxNDM0NzU3ZTkyZjRhNjZiMmQzYmRlMWZkNDFiNGY0NDAwNTAwMGRhMjIwNmQyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ijomFsiVuMBD9KqCA0sWBaT2I8QYPNrGtM98UrAimWU">
> Also I keep getting this issue in the terminal saying
> 
> `err: { api-1 | "type": "NotFoundException", api-1 | "message": "Connectors not found for current project!", api-1 | "stack": api-1 | NotFoundException: Connectors not found for current project! api-1 | at ProjectConnectorsService.getConnectorsByProjectId (/app/packages/api/dist/src/@core/project-connectors/project-connectors.service.js:91:23) api-1 | at async ProjectConnectorsController.getConnectorsFromProject (/app/packages/api/dist/src/@core/project-connectors/project-connectors.controller.js:39:16) api-1 | "response": { api-1 | "type": "Object", api-1 | "message": "Connectors not found for current project!", api-1 | "stack": api-1 | api-1 | "error": "Not Found", api-1 | "statusCode": 404 api-1 | }, api-1 | "status": 404, api-1 | "options": {}, api-1 | "name": "NotFoundException" api-1 | } api-1 | Req data is: { api-1 | id_user: '5de5e7f2-aee8-4114-b7e3-a1dc5e67e87a', api-1 | email: 'arkaprabha.mahata@adjoint.in', api-1 | first_name: 'Arkaprabha', api-1 | last_name: 'Mahata', api-1 | id_project: 'acb1a3a8-f868-42c4-9040-68db6be5057f' api-1 | }`
> 
> It would be very helpful if you can resolve this quickly. Thnak you again

When did you try to do it ? Because I merged a PR fixing this issue 30min ago

**Comment by mit-27** [comment]
> > Hi, I have been trying to create a magic link to create a CRM integration but after the link is generated no applications are showing up as can bee seen in the screenshot below.
> > <img alt="Screenshot 2024-06-06 at 6 30 23 PM" width="1440" src="https://private-user-images.githubusercontent.com/26703458/337273704-1f7626d8-ee02-471f-819a-6cbaccd87e07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Nzk5MzMsIm5iZiI6MTcxNzY3OTYzMywicGF0aCI6Ii8yNjcwMzQ1OC8zMzcyNzM3MDQtMWY3NjI2ZDgtZWUwMi00NzFmLTgxOWEtNmNiYWNjZDg3ZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEzMTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTE1YjY4NTgyMWNmNDcxNDM0NzU3ZTkyZjRhNjZiMmQzYmRlMWZkNDFiNGY0NDAwNTAwMGRhMjIwNmQyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ijomFsiVuMBD9KqCA0sWBaT2I8QYPNrGtM98UrAimWU">
> > Also I keep getting this issue in the terminal saying
> > `err: { api-1 | "type": "NotFoundException", api-1 | "message": "Connectors not found for current project!", api-1 | "stack": api-1 | NotFoundException: Connectors not found for current project! api-1 | at ProjectConnectorsService.getConnectorsByProjectId (/app/packages/api/dist/src/@core/project-connectors/project-connectors.service.js:91:23) api-1 | at async ProjectConnectorsController.getConnectorsFromProject (/app/packages/api/dist/src/@core/project-connectors/project-connectors.controller.js:39:16) api-1 | "response": { api-1 | "type": "Object", api-1 | "message": "Connectors not found for current project!", api-1 | "stack": api-1 | api-1 | "error": "Not Found", api-1 | "statusCode": 404 api-1 | }, api-1 | "status": 404, api-1 | "options": {}, api-1 | "name": "NotFoundException" api-1 | } api-1 | Req data is: { api-1 | id_user: '5de5e7f2-aee8-4114-b7e3-a1dc5e67e87a', api-1 | email: 'arkaprabha.mahata@adjoint.in', api-1 | first_name: 'Arkaprabha', api-1 | last_name: 'Mahata', api-1 | id_project: 'acb1a3a8-f868-42c4-9040-68db6be5057f' api-1 | }`
> > It would be very helpful if you can resolve this quickly. Thnak you again
> 
> I just merged a PR
> 
> > Hi, I have been trying to create a magic link to create a CRM integration but after the link is generated no applications are showing up as can bee seen in the screenshot below.
> > <img alt="Screenshot 2024-06-06 at 6 30 23 PM" width="1440" src="https://private-user-images.githubusercontent.com/26703458/337273704-1f7626d8-ee02-471f-819a-6cbaccd87e07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Nzk5MzMsIm5iZiI6MTcxNzY3OTYzMywicGF0aCI6Ii8yNjcwMzQ1OC8zMzcyNzM3MDQtMWY3NjI2ZDgtZWUwMi00NzFmLTgxOWEtNmNiYWNjZDg3ZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEzMTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTE1YjY4NTgyMWNmNDcxNDM0NzU3ZTkyZjRhNjZiMmQzYmRlMWZkNDFiNGY0NDAwNTAwMGRhMjIwNmQyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ijomFsiVuMBD9KqCA0sWBaT2I8QYPNrGtM98UrAimWU">
> > Also I keep getting this issue in the terminal saying
> > `err: { api-1 | "type": "NotFoundException", api-1 | "message": "Connectors not found for current project!", api-1 | "stack": api-1 | NotFoundException: Connectors not found for current project! api-1 | at ProjectConnectorsService.getConnectorsByProjectId (/app/packages/api/dist/src/@core/project-connectors/project-connectors.service.js:91:23) api-1 | at async ProjectConnectorsController.getConnectorsFromProject (/app/packages/api/dist/src/@core/project-connectors/project-connectors.controller.js:39:16) api-1 | "response": { api-1 | "type": "Object", api-1 | "message": "Connectors not found for current project!", api-1 | "stack": api-1 | api-1 | "error": "Not Found", api-1 | "statusCode": 404 api-1 | }, api-1 | "status": 404, api-1 | "options": {}, api-1 | "name": "NotFoundException" api-1 | } api-1 | Req data is: { api-1 | id_user: '5de5e7f2-aee8-4114-b7e3-a1dc5e67e87a', api-1 | email: 'arkaprabha.mahata@adjoint.in', api-1 | first_name: 'Arkaprabha', api-1 | last_name: 'Mahata', api-1 | id_project: 'acb1a3a8-f868-42c4-9040-68db6be5057f' api-1 | }`
> > It would be very helpful if you can resolve this quickly. Thnak you again
> 
> When did you try to do it? Because I merged a PR fixing this issue 30min ago

Hello @arkanoid17, please use the given credentials for login. The issue will be resolved for these credentials.

Email - local@panora.dev
Password - panora123

**Comment by naelob** [comment]
Fixed with the new PR merged

**Comment by naelob** [comment]
Fixed with the new PR merged
