### ISSUE TITLE
feat: Add integration with: BambooHR (ATS)

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#503]
### What type of software do you want to build integrations with?

Other

### Which specific platforms would you integrate with?

BambooHR (ATS)

### Which specific objects would you integrate with?

- [ ] Candidates (GET)
- [ ] Applications (GET)
- [ ] Attachments (GET)  (not sure the Bamboo API supports that)
- [ ] Jobs
- [ ] Offices
- [ ] Interview Stages
- [ ] Users

### Do you anticipate to mostly read, or write data?

Read mostly

### Please share any detail you want here

**Pull vs Realtime data:** syncs every 3 hours max is okay for customer. 

If needed, you can [ask Panora's team for credentials here](https://airtable.com/appUOCIdiEcBaZWMd/pagFdwXOv5BsVPFv0/form)

**Comment by sourabh100x** [comment]
Could you please assign this issue to me?

**Comment by naelob** [comment]
> have read integration guide, would love to contribute. could you please assign this issue to me?

Come on discord i need to give you a ressource

**Comment by sourabh100x** [comment]
got errors while setting up locally. can anyone help??

**Comment by Dozie2001** [comment]
@sourabh100x are you still wokrking on this

**Comment by sourabh100x** [comment]
@Dozie2001 nope you can work on this

**Comment by Dozie2001** [comment]
@rflihxyz it looks like this has been built out already

**Comment by iamitpal** [comment]
please add a proper guide to setup locally

**Comment by naelob** [comment]
> please add a proper guide to setup locally

Hey ! Did you read this section of the docs ? 
https://docs.panora.dev/open-source/self-host-guide

**Comment by Katsuya21** [comment]
Hey! I would like to work on this. Please assign it to me.

**Comment by irwansyahwii** [comment]
@naelob I sent you messages on Discord, please check

**Comment by irwansyahwii** [comment]
@naelob I created a PR to fix limit query: https://github.com/panoratech/Panora/pull/680
