### ISSUE TITLE
feat: Add integration with: Dropbox

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#536]
### What type of software do you want to build integrations with?

File Storage

### Which specific platforms would you integrate with?

Dropbox

### Which specific objects would you integrate with?

Drive
File
Folder
Group 
User
Permission
Shared Link

### Do you anticipate to mostly read, or write data?

Read mostly

**Comment by rohankumarchaudhary67** [comment]
Hi @naelob , I already work on that issue, please assign to me.....

**Comment by naelob** [comment]
> Hi @naelob , I already work on that issue, please assign to me.....

Thank you tomorrow the vertical is uploaded ! I'lll ping you so you can start working on it !

**Comment by rohankumarchaudhary67** [comment]
Okk thanks for that

> > Hi @naelob , I already work on that issue, please assign to me.....
> 
> Thank you tomorrow the vertical is uploaded ! I'lll ping you so you can start working on it !

**Comment by naelob** [comment]
> Okk thanks for that
> 
> > > Hi @naelob , I already work on that issue, please assign to me.....
> > 
> > 
> > Thank you tomorrow the vertical is uploaded ! I'lll ping you so you can start working on it !

Hey @rohankumarchaudhary67 Sorry for the delay ! It is now ready and you can work on it ! You may need credentials for the oAuth app. Join the discord and I'll share that so you can iterate fast.

**Comment by rohankumarchaudhary67** [comment]
Okk

**Comment by naelob** [comment]
> Okk

Come on discord I'll send you credentials of oauth so you can be set up !

**Comment by naelob** [comment]
Hey @rohankumarchaudhary67  It's been a while ! Do you need help ?

**Comment by kolharsam** [comment]
@naelob @rflihxyz I can pick this up if you folks are okay with it?

**Comment by kolharsam** [comment]
@naelob @rflihxyz

Thank you for assigning this to me! 🙏 

 could you please let me know how you can share the credentials (if needed) ?

**Comment by amuwal** [comment]
@naelob can you assign me this.
