### ISSUE TITLE
feat: Add integration with: OneDrive

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#537]
### What type of software do you want to build integrations with?

File Storage

### Which specific platforms would you integrate with?

One Drive

### Which specific objects would you integrate with?

Drive
File
Folder
Group 
User
Permission
Shared Link

### Do you anticipate to mostly read, or write data?

Read mostly

**Comment by nigrumpirate** [comment]
have read integration guide, would love to contribute. could you please assign this issue to me?

**Comment by naelob** [comment]
> Would love to contribute. could you please assign this issue to me?

Done ! Please wait tomorrow so I push the file storage vertical !

**Comment by naelob** [comment]
@nigrumpirate Hey ! Sorry for the delay ! You can now work on the connector, if yopu need help I'm available on Discordd feel free to reach out !

**Comment by naelob** [comment]
Hey @nigrumpirate Do you need help ? Thanks for your feedback !

**Comment by manthan-sharma-23** [comment]
Working on it , can you assign the issue
