### ISSUE TITLE
feat: Add integration with: Box

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#538]
### What type of software do you want to build integrations with?

File Storage

### Which specific platforms would you integrate with?

Box

### Which specific objects would you integrate with?

Drive
File
Folder
Group 
User
Permission
Shared Link

### Do you anticipate to mostly read, or write data?

Read mostly

**Comment by blackviking27** [comment]
Hey @naelob
Would like to work on this, Could you also mention home page for BOX

**Comment by naelob** [comment]
> Hey @naelob Would like to work on this, Could you also mention home page for BOX

Im already on it as it wil be showcased for other contributors !

I'll open enw connectors this week so you can take them !

**Comment by blackviking27** [comment]
Ok, cool
