### ISSUE TITLE
feat: Add integration with: Google Drive

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#539]
### What type of software do you want to build integrations with?

File Storage

### Which specific platforms would you integrate with?

Google Drive

### Which specific objects would you integrate with?

Drive
File
Folder
Group 
User
Permission
Shared Link

### Do you anticipate to mostly read, or write data?

Read mostly

If needed, you can [ask Panora's team for credentials here](https://airtable.com/appUOCIdiEcBaZWMd/pagFdwXOv5BsVPFv0/form)

**Comment by Haritarth** [comment]
Hello, I'd like to work on this

**Comment by naelob** [comment]
> Hello, I'd like to work on this
> 
> 

Hey thanks ! Can you wait tomorrow ? Im going to push the vertical today !

**Comment by naelob** [comment]
@Haritarth Hey ! Sorry for the long delay ! You can now work on the integration ! Yu may need oAuth credentials for that. Join the discord and I'll share it there !

**Comment by STSonyThomas** [comment]
Hey is this issue still open? If then I could get on? @naelob

**Comment by vengatesh99** [comment]
Hey Panora team, can my team also work on this or it's already assigned to someone ?

**Comment by rflihxyz** [comment]
Hey @vengatesh99 , just assigned you the issue!

**Comment by vengatesh99** [comment]
Thanks, @rflihxyz

**Comment by rflihxyz** [comment]
Need any help @vengatesh99 ?

**Comment by vengatesh99** [comment]
I am just going through the docs and getting familiar with codebase. I will reach out to you if I need something! Thanks

**Comment by Npcodes1** [comment]
Is this one still available? Trying to find a project for the Headstarter AI fellowship so hoping to connect with someone to learn more about this.

**Comment by vengatesh99** [comment]
Hi @Npcodes1 , our team at headstarter is currently working on this. I guess more than one team can work on it as well. @rflihxyz could you please confirm. Thanks!

**Comment by naelob** [comment]
> Hi @Npcodes1 , our team at headstarter is currently working on this. I guess more than one team can work on it as well. @rflihxyz could you please confirm. Thanks!

It's been a month now. I will give it to @Npcodes1 so she can try !
