### ISSUE TITLE
feat: Add integration with WealthBox (CRM)

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#555]
### What type of software do you want to build integrations with?

CRM

### Which specific platforms would you integrate with?

[Wealthbox](https://www.wealthbox.com/)

### Which specific objects would you integrate with?

- [ ] Contacts 
- [ ] Tasks
- [ ] Opportunities
- [ ] Notes

### Do you anticipate to mostly read, or write data?

Read and write

If needed, you can [ask Panora's team for credentials here](https://airtable.com/appUOCIdiEcBaZWMd/pagFdwXOv5BsVPFv0/form)

**Comment by Aryanshu919** [comment]
Could you assign this to me? I want to work on this.

**Comment by rflihxyz** [comment]
Hey @Aryanshu919 , just assigned you the issue!

**Comment by naelob** [comment]
@Aryanshu919 Hey ! Do you need help setting up the Oauth app ? If any help is needed join the discord and I'll send the credentials !

**Comment by Aryanshu919** [comment]
@naelob Yes, sure. I already joined the Discord.

**Comment by mohammedyunus2002** [comment]
if @Aryanshu919 is not working on this issue i would like to work on this

**Comment by Aryanshu919** [comment]
@mohammedyunus2002 I am working on this issue. You can pick another one
