### ISSUE TITLE
feat: Add integration with: Greenhouse (ATS)

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#569]
### What type of software do you want to build integrations with?

ATS

### Which specific platforms would you integrate with?

Greenhouse

### Which specific objects would you integrate with?
https://docs.merge.dev/integrations/ats/greenhouse/provider-interactions/

### Do you anticipate to mostly read, or write data?

Read and write

**Comment by MayankTamakuwala** [comment]
Can you please assign this task to me?

**Comment by AJAYBHAWARIYA** [comment]
Can you do this task in collab with @MayankTamakuwala as well?

**Comment by naelob** [comment]
Thank you guys for the support !

**Comment by naelob** [comment]
> Can you assign this task to me in collab with @MayankTamakuwala as well?

Hey @AJAYBHAWARIYA Do you need help ? thanks for your feedback !

**Comment by MayankTamakuwala** [comment]
Hey @naelob! Yes, I need help. Can we meet on discord voice chat right now?

**Comment by naelob** [comment]
Yes lets go !
