### ISSUE TITLE
docs: Developer Experience Improvements

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#608]
-  Update magic_links routes to be REST compliant
- Pick one date + timestamp format for all created_at, modified_at 
- Add proper unified object examples in SDKs (ex: missing [here](https://docs.panora.dev/ats/activities/create-a-activity))
- Fix non-compliant REST routes: 
    - https://docs.panora.dev/api-reference/linked_users/retrieve
- Rename all pages following format: Action (Retrieve, List, Update, Delete, Create) + Unified object (plural)
- Update Webhooks events list, and automate events list generation

**Comment by naelob** [comment]
> * Update magic_links routes to be REST compliant
> * Pick one date + timestamp format for all created_at, modified_at
> * Add proper unified object examples in SDKs (ex: missing [here](https://docs.panora.dev/ats/activities/create-a-activity))
> * Fix non-compliant REST routes:
>   
>   * https://docs.panora.dev/api-reference/linked_users/retrieve
> * Rename all pages following format: Action (Retrieve, List, Update, Delete, Create) + Unified object (plural)
> * Update Webhooks events list, and automate events list generation

im on it opening the pr tomorrow !

**Comment by naelob** [comment]
- [ ]   Update magic_links routes to be REST compliant

- [ ] Pick one date + timestamp format for all created_at, modified_at 
- [ ] Add proper unified object examples in SDKs (ex: missing [here](https://docs.panora.dev/ats/activities/create-a-activity))
- [ ] Fix non-compliant REST routes: 
    - https://docs.panora.dev/api-reference/linked_users/retrieve
- [ ] Rename all pages following format: Action (Retrieve, List, Update, Delete, Create) + Unified object (plural)
- [ ] Update Webhooks events list, and automate events list generation
