### ISSUE TITLE
feat: Add integration with: Lever

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#617]
### What type of software do you want to build integrations with?

Other

### Which specific platforms would you integrate with?

- [ ]  Candidates 
- [ ]  Department
- [ ]  Applications 
- [ ]  Attachments 
- [ ]  Activity
- [ ]  Jobs
- [ ]  Job Interview Stages
- [ ]  Users
- [ ]  Tag
- [ ]  Scorecard
- [ ]  RejectReason
- [ ]  Office
- [ ]  Offer
- [ ]  EEOCS

### Do you anticipate to mostly read, or write data?

Read and write

**Comment by winstondmasi** [comment]
Hi Nael, you can assign this to me, Thanks!

**Comment by TinglyTingly** [comment]
Hello!  My team is working on the Lever integration.  The objects that you want back are:

- [ ] Candidates
- [ ]  Department
- [ ]  Applications
- [ ]  Attachments
- [ ]  Activity
- [ ]  Jobs
- [ ]  Job Interview Stages
- [ ]  Users
- [ ]  Tag
- [ ]  Scorecard
- [ ]  RejectReason
- [ ]  Office
- [ ]  Offer
- [ ]  EEOCS

Lever has wayyyy more endpoints than this, but these are the only ones to be mapped, correct?

**Comment by megane18** [comment]
Hi @naelob, my team and I would like to work on this issue. We are doing Track C for the headstarter fellowship. Is it possible to get assigned to this? We are a group of four @NareenAsad, @Will15800, @musabsarmadmir.

**Comment by ankithas-09** [comment]
Hi @naelob , can you please assign this to me as a part of headstarter Fellow

**Comment by TinglyTingly** [comment]
Hello. I see a few comments from headstarter fellows about reassigning this integration. My team is still actively working on this, so please don't remove winstondmasi as assignee. Thank you.
