### ISSUE TITLE
feat: Add integration with: Workday

### ISSUE THREAD

**Issue by vengatesh99** [panoratech/Panora#623]
### What type of software do you want to build integrations with?

HRIS

### Which specific platforms would you integrate with?

Workday

### Which specific objects would you integrate with?

https://docs.merge.dev/integrations/ats/workday/provider-interactions/
(ATS)

### Do you anticipate to mostly read, or write data?

Read and write

**Comment by lloydchang** [comment]
@vengatesh99 How is https://github.com/panoratech/Panora/issues/623 different than https://github.com/panoratech/Panora/blob/main/packages/api/src/%40core/connections/ats/services/workday/workday.service.ts ? Thanks!

**Comment by naelob** [comment]
> @vengatesh99 How is #623 different than https://github.com/panoratech/Panora/blob/main/packages/api/src/%40core/connections/ats/services/workday/workday.service.ts ? Thanks!

This file is just the connection file not the integration !

**Comment by vengatesh99** [comment]
Thank you so much  @naelob !
