### ISSUE TITLE
feat: Add integration with: Microsoft Dynamics 365 Sales (CRM)

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#624]
### What type of software do you want to build integrations with?

CRM

### Which specific platforms would you integrate with?

Microsoft Dynamics 365 Sales

### Which specific objects would you integrate with?

- [ ] Companies
- [ ] Contacts
- [ ] Engagements
- [ ] Notes
- [ ] Deals
- [ ] Tasks
- [ ] Users

### Do you anticipate to mostly read, or write data?

Read mostly

### Please share any detail you want here

Find our contributors guide [here](https://docs.panora.dev/open-source/contributors/setup) ✨

**Comment by naelob** [comment]
> /attempt #624
> 
> [Algora profile](https://console.algora.io/@/ezhil56x)	Completed bounties	Tech	Active attempts	Options
> @ezhil56x	41 bounties from 12 projects	
> JavaScript, TypeScript,
> Rust & more
> [Cancel attempt](https://console.algora.io/api/bounties/clzk4z1up000gmd09ph7ebcmj/cancel-attempt)

Let me merge a PR so you have the connection of Dynamics and you just have to build the mapper !

**Comment by naelob** [comment]
> > /attempt #624
> > [Algora profile](https://console.algora.io/@/ezhil56x)	Completed bounties	Tech	Active attempts	Options
> > @ezhil56x	41 bounties from 12 projects
> > JavaScript, TypeScript,
> > Rust & more
> > [Cancel attempt](https://console.algora.io/api/bounties/clzk4z1up000gmd09ph7ebcmj/cancel-attempt)
> 
> Let me merge a PR so you have the connection of Dynamics and you just have to build the mapper !

Done you can work on it !

**Comment by ezhil56x** [comment]
Gone through the local dev setup and the codebase will start implementation soon

**Comment by rflihxyz** [comment]
Great! Let us know if you need support

**Comment by MuhmdAjeer** [comment]
hey @rflihxyz, i would like to work on this

**Comment by ezhil56x** [comment]
> hey @rflihxyz, i would like to work on this 
> 

I'm working on it

**Comment by neehhaa06** [comment]
Hello!! @rflihxyz, I would like to work on this. :)

**Comment by rflihxyz** [comment]
Hey Neha, assigned :)
