### ISSUE TITLE
feat: Add integration with: Webflow (ecommerce)

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#640]
### What type of software do you want to build integrations with?

Ecommerce

### Which specific platforms would you integrate with?

Webflow

### Which specific objects would you integrate with?

- [ ] Customers
- [ ] Orders
- [ ] Products

### Do you anticipate to mostly read, or write data?

Read and write

**Comment by Npcodes1** [comment]
Hello, I'm trying to pick a project for the Headstarter AI fellowship so hoping to connect with someone to learn more about this.

**Comment by amuwal** [comment]
@naelob @rflihxyz I would  like to work on this.

**Comment by rflihxyz** [comment]
Hey @amuwal , assigned!

**Comment by megane18** [comment]
Hi, my team and I would like to work on this issue. Could we please get assigned to it? We are a group of four @NareenAsad, @Will15800, @musabsarmadmir.

**Comment by amuwal** [comment]
> Hi, my team and I would like to work on this issue. Could we please get assigned to it? We are a group of four @NareenAsad, @Will15800, @musabsarmadmir.

Hey @megane18, I am already working on this.

**Comment by Npcodes1** [comment]
I was already assigned too.
