### ISSUE TITLE
feat: Add integration with: SalesForce

### ISSUE THREAD

**Issue by rflihxyz** [panoratech/Panora#654]
### What type of software do you want to build integrations with?

CRM

### Which specific platforms would you integrate with?

Salesforce

### Which specific objects would you integrate with?

- [ ] Companies
- [ ] Contacts
- [ ] Engagements
- [ ] Notes
- [ ] Deals
- [ ] Tasks
- [ ] Users

### Do you anticipate to mostly read, or write data?

Read and write

**Comment by crocmons** [comment]
hey hi @rflihxyz I want to work on this issue..can you assign it to me?

**Comment by zih19** [comment]
In the salesforce company, when I take a look at its API, it does not contain categories like companies, deals, and engagement. Do you think we can find others alternative to these three parts?

**Comment by zih19** [comment]
For instance, Engagement can be treated as EngagementChannelTypes, and Deals can be identified as opportunities.

**Comment by naelob** [comment]
@zih19 You must use Soap/u/54.0/{company_id} route for all objects!
