### ISSUE TITLE
Dev Setup for Mac (Silicon Chip)

### ISSUE THREAD

**Issue by abskrj** [panoratech/Panora#684]
**Describe the bug**
While setting it up on 2 Mac (silicon chips), I have got issue in building bcrypt package, as we have to build it from source. 

**To Reproduce**
1. Go to root folder
2. Run `docker compose -f docker-compose.dev.yml up`

**Expected behavior**
It should run the dev server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.2
 - Version: NA

**Comment by abhinayy0** [comment]
@abskrj Can you post some screenshots of the container logs, which are not opening, or of the error you face while building bcrypt.

**Comment by abskrj** [comment]
Closing as it got resolved after a cleaning Docker cache
