### ISSUE TITLE
feat: Add integration with: Sharepoint

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#691]
### What type of software do you want to build integrations with?

File Storage

### Which specific platforms would you integrate with?

Sharepoint

### Which specific objects would you integrate with?

Drive
File
Folder
Group
User
Permission

### Do you anticipate to mostly read, or write data?

Read mostly

**Comment by amuwal** [comment]
Hi @naelob , can I get assigned to this.

**Comment by tshephomotlhale** [comment]
Hi @naelob , can I get assigned to this.

**Comment by amuwal** [comment]
> Hi @naelob , can I get assigned to this.

Hi @tshephomotlhale, I am already working on this.

**Comment by neehhaa06** [comment]
Hello @naelob :)

fix: #691

Please, I think first ensure proper authentication with valid credentials and necessary permissions. Review SharePoint’s API documentation to use the correct endpoints and handle errors effectively. Align your data model with SharePoint’s structure and verify that permissions are set correctly for users and groups.
