### ISSUE TITLE
Create Tests Rules (e2e, unit tests)

### ISSUE THREAD

**Issue by naelob** [panoratech/Panora#7]
One may want to use https://vitest.dev/ !

**Comment by naelob** [comment]
https://vitest.dev/

**Comment by naelob** [comment]
https://tailwindcss.com/
https://github.com/pmndrs/zustand
https://nextjs.org/
https://github.com/emotion-js/emotion

**Comment by naelob** [comment]
> Hi @naelob , it would great to break this into task lists for ease. Like list of components to be tested, e2e tests, etc. It might help in working on them one step at a time. More info here https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

unfortunately i tried adding tasks but it feels like its not working ...

**Comment by naelob** [comment]
actually we'd like to test first the api which is the core backend service of the project.
https://github.com/panoratech/Panora/tree/main/packages/api
A proper unit & e2e tests of all routes would be amazing !
You can start step by step of course!

**Comment by c0d33ngr** [comment]
Alright
